title: OH MY CODE !!
email: han103506@gmail.com
description: Toward best
baseurl: "" 
url: "" 

twitter_username: seungwook_hahn
github_username:  SeungukHan
linkedin_username: seungwook-han-3787481a3

plugins:
  - jekyll-feed
  - jekyll-seo-tag
