title: OH MY CODE!!
email: han103506@gmail.com
description: Toward best
baseurl: "" 
url: "" 

author: Seung-Wook Han
twitter_username: seungwook_hahn
github_username:  SeungukHan
linkedin_username: seungwook-han-3787481a3

collections:
  books:
    output: true
  notes:
    output: true
  blogs:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
